services:
  db:
    image: postgres:18.2-alpine3.23
    container_name: scheduly-db
    restart: always

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 1s
      timeout: 5s
      retries: 5

    volumes:
      - database:/var/lib/postgresql

  backend:
    image: dieginin/scheduly-backend
    container_name: scheduly-backend
    restart: always

    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      FRONTEND_URL: ${FRONTEND_URL}

    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('net').connect(process.env.PORT,'127.0.0.1').on('connect',()=>process.exit(0)).on('error',()=>process.exit(1))",
        ]
      interval: 1s
      timeout: 5s
      retries: 5

    networks:
      - default
      - proxy

  frontend:
    image: dieginin/scheduly-frontend
    container_name: scheduly-frontend
    restart: always

    environment:
      VITE_SCHEDULY_API_URL: ${VITE_SCHEDULY_API_URL}

    depends_on:
      backend:
        condition: service_healthy

    networks:
      - default
      - proxy

volumes:
  database:

networks:
  proxy:
    external: true
