services:
  db:
    image: postgres:18.2-alpine3.23
    container_name: scheduly-db
    restart: always

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 1s
      timeout: 5s
      retries: 5

    volumes:
      - database:/var/lib/postgresql

  backend:
    image: dieginin/scheduly-backend
    container_name: scheduly-backend
    restart: always

    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}

    depends_on:
      db:
        condition: service_healthy

    ports:
      - ${PORT}:${PORT}

volumes:
  database:
